### ISSUE TITLE
Prepare OpenLab Attributions plugin for release and include in CBOX OpenLab

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#341]
Here are the relevant tickets from the City Tech OpenLab:

Original ticket for creating the plugin: http://redmine.citytech.cuny.edu/issues/2505
Ticket for improvements: http://redmine.citytech.cuny.edu/issues/2916

**Comment by boonebgorges** [comment]
@Mamaduka Could you take the lead here? It looks like the plugin is largely ready. Make sure it's l18n-ready, maybe abstract out some of the cache-busting strings to make release a bit easier, stuff like that. I've created a repo at https://github.com/openlab-at-city-tech/openlab-attributions, and you should have Maintain privileges.

@bree-z Do we want to release this plugin on the wordpress.org plugin repo? George can correct me if I'm wrong, but I think that the plugin will work on any WP installation - no CBOX or BP required. 

If that's the case, then George, could you also create a minimal wordpress.org-friendly readme.txt? Then either you or I will have to go through the plugin submission process.

Once the plugin is in its openlab-attributions repo, we should add it to the CBOX package, serving from github.com, so that we can do some team testing on the openlabdev.commonsinabox.org site. We can swap out with the wordpress.org URL if and when the plugin is being distributed from there.

**Comment by Mamaduka** [comment]
Adding l18n is the only thing I can think of that we're missing. I will start working on it after new improvements.

That's correct, the plugin can work on any WP installation.

P.S. I want to change a directory structure and match the practice usually used in Block Editor plugins. This might be a good time to do it.

**Comment by bree-z** [comment]
My understanding is that we wanted to release this plugin on the wordpress.org plugin repo, but I'd just like to double check.

@charliemedwards could you confirm if that's correct?

Thanks!

**Comment by Mamaduka** [comment]
Thank you for the update, @bree-z.

@boonebgorges, I think only string l18n is missing on the JS side, and we'll need `readme.txt` for submission. I'll push the l18n update to the repo this week.

**Comment by boonebgorges** [comment]
I've run through the plugin and set up all the necessary i18n infrastructure.

In order to release on wordpress.org, we need a readme.txt, possibly a new name (we previously opted for `wp-grade-comments` rather than `openlab-grade-comments`), and we need to run through the wordpress.org application process. I don't have the bandwidth to complete this process before the CBOX 1.3 release, so for now I'll be pulling the plugin from GitHub.

**Comment by bree-z** [comment]
Hi Boone, 

I don't see the attribution icon anywhere in the block editor toolbar when the plugin is activated on a single site or network activated.  

See for example, this site where it's activated: https://openlabdev.commonsinabox.org/summer-2021-course/

Apologies if I'm missing anything!

<img width="994" alt="Screen Shot 2021-07-26 at 2 08 14 PM" src="https://user-images.githubusercontent.com/7189824/127042103-700eafaa-60f9-4002-a1a3-f8db00bbdcdf.png">

**Comment by boonebgorges** [comment]
No, you're not missing anything. I misunderstood the way that the plugin build process works, and I tagged a version of the plugin that didn't have the necessary built assets. I've fixed this in 2.0.0-beta2, which is now ready to test on openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
Thanks Boone. I still don't see the attribution icon in the block editor. 

I'm not sure if this is something I did though. First I network activated it here: https://openlabdev.commonsinabox.org/wp-admin/network/plugins.php

Then I saw that it's actually one of the member site plugins here: https://openlabdev.commonsinabox.org/wp-admin/network/admin.php?page=cbox-plugins&type=install-only where I saw a link asking me to deactivate it. 

I clicked on the link, and then I activated it in the member site plugins tab. But, I still don't see it in the block editor on individual sites.

Sorry if I messed something up!

**Comment by boonebgorges** [comment]
It's hard for me to understand what's happened in the sequence of events that you've described, but here's what I did:

- At https://openlabdev.commonsinabox.org/summer-2021-course/wp-admin/plugins.php, activate OpenLab Attributions
- Edit a post such as https://openlabdev.commonsinabox.org/summer-2021-course/wp-admin/post.php?post=39&action=edit
- Highlight a word. The icon appears.

**Comment by bree-z** [comment]
Whoops, sorry about that Boone! I forgot that when I activate member site plugins, it's not the same as network activating a plugin. 

I was able to activate and test. Looks good, thanks!
