### ISSUE TITLE
New Post Sharing Options plugin throws an error with Full Site Editing themes

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#498]
The new Post Sharing Options plugin that is part of OpenLab generates an error message anytime the Full Site Editor is opened with a FSE theme.

Here's an example screenshot:

<img width="1191" alt="Screenshot 2024-08-27 at 7 02 20 PM" src="https://github.com/user-attachments/assets/de6f6f6e-e4bc-46ef-a1ed-c3d145121995">

**Comment by boonebgorges** [comment]
Thanks for flagging this. It was fixed for City Tech in http://redmine.citytech.cuny.edu/issues/3415 but not ported to cbox-openlab-core. I've done so in 6811e18. If you want to test, make sure you also run the build step (`npm run build-js:site-templates`) or grab https://github.com/cuny-academic-commons/cbox-openlab-core/commit/9249a19410532579a3a92d2a5bbe2479bd945ffd

**Comment by bree-z** [comment]
I don't see this error anywhere on sites with a FSE theme enabled.

**Comment by beckej13820** [comment]
Hi @bree-z ,

I can confirm I still see this on my sites. To reproduce:

1. Make sure you are using FSE theme, such as twenty twenty four or twenty twenty five
2. Click on "Edit Site" to enter the Full Site Editor
3. On the left hand side, open the templates menu.
4. Select a template to modify, such as Blog Home, Index, or Single Posts
5. Observe the error

![Image](https://github.com/user-attachments/assets/208e59c9-760c-4d96-a0d0-c141d1f041bd)

**Comment by beckej13820** [comment]
Hey Boone, 

I think I misunderstood @bree-z message. I thought she was saying that integration of the patch into an upcoming release wasn't required because she couldn't replicate on the current version of OpenLab.

I didn't do the hot-patch because I was unsure if npm dependencies were installed on my site.

Now that we have moved to managed hosting with reclaim, I will give them the patch and your directions and let them do the dirty work. ;-)
